log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:12345@localhost:5432/usdctrackerdb

ethereum_connection:
  url: wss://mainnet.infura.io/ws/v3/...

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: usdc-tracker-svc
  service_port: 80
